version = 1

# Configuration files
[[annotations]]
path = ["**/*.yml", "**/*.yaml", "**/*.json", "**/*.mod", "**/*.sum", "**/*.lock", "**/*.toml", ".gitignore", "**/.gitignore", "Makefile", "**/PklProject", "Opkgfile"]
SPDX-FileCopyrightText = "© 2025 Platform Engineering Labs Inc."
SPDX-License-Identifier = "FSL-1.1-ALv2"

# Shell scripts in scripts/ directory
[[annotations]]
path = ["scripts/**/*.sh"]
SPDX-FileCopyrightText = "© 2025 Platform Engineering Labs Inc."
SPDX-License-Identifier = "FSL-1.1-ALv2"

# Documentation files
[[annotations]]
path = ["**/*.md", "**/*.html"]
SPDX-FileCopyrightText = "© 2025 Platform Engineering Labs Inc."
SPDX-License-Identifier = "FSL-1.1-ALv2"

# Binary and generated test files
[[annotations]]
path = ["**/*.zip", "**/*.pcf", "**/*.log", "**/*.txt", "**/VERSION"]
SPDX-FileCopyrightText = "© 2025 Platform Engineering Labs Inc."
SPDX-License-Identifier = "FSL-1.1-ALv2"

# Dockerfile
[[annotations]]
path = ["**/Dockerfile*"]
SPDX-FileCopyrightText = "© 2025 Platform Engineering Labs Inc."
SPDX-License-Identifier = "FSL-1.1-ALv2"
